# Generated by Django 3.0.3 on 2021-03-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveUserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.PositiveIntegerField()),
                ('campaign', models.PositiveIntegerField()),
                ('t_number', models.PositiveIntegerField()),
                ('calls', models.PositiveIntegerField()),
                ('Tags', models.PositiveIntegerField()),
                ('Webhooks', models.PositiveIntegerField()),
                ('p_number', models.PositiveIntegerField()),
                ('r_number', models.PositiveIntegerField()),
                ('component', models.CharField(max_length=100)),
            ],
        ),
    ]
