# Generated by Django 3.0.3 on 2021-03-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0003_auto_20210315_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveuserdata',
            name='components',
        ),
    ]
