# Generated by Django 3.0.3 on 2021-03-15 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0004_remove_saveuserdata_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveuserdata',
            name='component',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
