# Generated by Django 3.0.3 on 2021-03-15 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetail', '0005_saveuserdata_component'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveuserdata',
            old_name='component',
            new_name='components',
        ),
    ]
